version = 1

[[annotations]]
path = "assets/jip_icon.svg"
SPDX-FileCopyrightText = [
    "2019 Calvin Rose and contributors",
    "2026 Martin Michel <martin@famic.de>"
]
SPDX-License-Identifier = "MIT OR CC-BY-SA-4.0"

[[annotations]]
path = "test/ics-files/*"
SPDX-FileCopyrightText = "2026 Martin Michel <martin@famic.de>"
SPDX-License-Identifier = "CC0-1.0"
